### ISSUE TITLE
Warning in console

### ISSUE THREAD

**Issue by zeemohamed7** [AliHussain-arch/TASK-MANAGER-GROUP-PROJECT#7]
https://github.com/AliHussain-arch/TASK-MANAGER-GROUP-PROJECT/blob/9d99f1181e86b9be2dd9d4806b74eb69083ab76d/FRONTEND/src/components/ProjectComponents/projectItem/projectItem.jsx#L71
 
Getting a Warning: Invalid DOM property `srcset`. Did you mean `srcSet`?

 use srcSet instead of srcset

**Comment by AliHussain-arch** [comment]
I didn't add the images ask fadel

**Comment by zeemohamed7** [comment]
GitHub issues serve as a collaborative forum for the entire repository community. Directly contacting each contributor about their work may not be practical, as I don't know who wrote what. These issues are for all of you to check out.

**Comment by AliHussain-arch** [comment]
So should I inform him?

**Comment by AliHussain-arch** [comment]
Fixed the issue myself
