### ISSUE TITLE
Authorisation 

### ISSUE THREAD

**Issue by zeemohamed7** [AliHussain-arch/TASK-MANAGER-GROUP-PROJECT#8]
A user can access, delete and edit other user's projects and tasks

**Comment by AliHussain-arch** [comment]
How ?

**Comment by AliHussain-arch** [comment]
It is only possible if you are signed in, have the particular userId, particular projectId, and particular taskId

**Comment by AliHussain-arch** [comment]
What to fix ?

**Comment by AliHussain-arch** [comment]
Did what Denis said

**Comment by AliHussain-arch** [comment]
Issue fixed

**Comment by zeemohamed7** [comment]
Great! Thanks for fixing your backend authorization issue.
