### ISSUE TITLE
Avoid console.log() in the final app

### ISSUE THREAD

**Issue by zeemohamed7** [AliHussain-arch/TASK-MANAGER-GROUP-PROJECT#9]
https://github.com/AliHussain-arch/TASK-MANAGER-GROUP-PROJECT/blob/9d99f1181e86b9be2dd9d4806b74eb69083ab76d/FRONTEND/src/services/authService.js#L11

https://github.com/AliHussain-arch/TASK-MANAGER-GROUP-PROJECT/blob/9d99f1181e86b9be2dd9d4806b74eb69083ab76d/FRONTEND/src/components/Authentication/signIn/signIn.jsx#L17

https://github.com/AliHussain-arch/TASK-MANAGER-GROUP-PROJECT/blob/9d99f1181e86b9be2dd9d4806b74eb69083ab76d/FRONTEND/src/components/SemanticComponents/navbar/navbar.jsx#L9

"The back-end and front-end applications do not contain dead code, commented-out sections, or console logs."

**Comment by AliHussain-arch** [comment]
Removed the console.log() 
fixed the issue
